### PR TITLE
spec: update cockpit requirements

### PR DESCRIPTION
**Pull request by didib**
cockpit-system now Obsoletes cockpit-dashboard.

### CODE REVIEW

**Comment by didib** [comment]
Also commented about this in: https://github.com/cockpit-project/cockpit/pull/14905

**Comment by sandrobonazzola** [comment]
pushed #31 for dropping fedora 30 tests

**Comment by didib** [comment]
ci build

**Comment by didib** [comment]
Verified, by 'dnf reinstall' to CI build. (IMO we should do CI builds using timestamp+githash names, like other projects. NVM for now).

**Pull request merged**
